In [ ]:
# 필요 라이브러리 로딩
import numpy as np

In [2]:
# 임의의 값을 이용하여 Numpy 배열 생성
data = np.random.randn(2, 3)
data

array([[ 0.24477412,  0.82385609, -2.04824765],
       [ 0.00307638, -1.05915239,  1.8167682 ]])

In [3]:
# 배열 차원의 크기
data.shape

(2, 3)

In [4]:
# 배열에 저장된 데이터의 형
data.dtype

dtype('float64')

### ndarray 생성

In [8]:
data1 = [6, 7, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6, 7, 8, 0, 1])

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# 배열의 차원 확인
arr1.ndim

1

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [13]:
type(arr2)

numpy.ndarray

In [14]:
arr2.dtype

dtype('int32')

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# 차원은 튜플타입으로 받아야 한다.
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
# 파이썬의 range()
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
# dtype
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
arr1

array([1., 2., 3.])

In [23]:
arr2

array([1, 2, 3])

In [24]:
# astype() : 자료형을 캐스팅
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [25]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [27]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [28]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [29]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

### Numpy 배열의 산술 연산

In [31]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [33]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [35]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [36]:
arr2 = np.array([[0., 4., 1.], [7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [37]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [38]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

### 인덱싱과 슬라이싱

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[5]

5

In [42]:
#[start:end]
arr[5:8]

array([5, 6, 7])

In [43]:
arr[5:8] = 12

In [44]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [45]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [46]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [47]:
#[:] 전체요소
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [48]:
# 다차원 배열의 색인
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr2d[2]

array([7, 8, 9])

In [50]:
arr2d[0][2]

3

In [51]:
#[행, 열] or [start:end, start:end]
arr2d[0, 2]

3

In [52]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
old_value = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[0] = old_value
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr3d[1, 0]

array([7, 8, 9])

In [57]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [58]:
x[0]

array([7, 8, 9])

In [59]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [60]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [61]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [64]:
arr2d[1, :2]

array([4, 5])

In [65]:
arr2d[:2, 2]

array([3, 6])

In [66]:
arr2d[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 블리언 배열을 이용하기

In [68]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [69]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [70]:
data

array([[ 0.88053026, -1.02862681,  0.97283693, -0.66985979],
       [-0.18123833, -1.86329248,  0.34802926, -2.20922986],
       [ 0.16051297, -1.00486513,  0.68942233, -0.57080177],
       [-2.24668949,  1.22677784,  0.773863  ,  1.27273805],
       [ 0.9174606 , -1.88353752,  0.11698041,  0.28134936],
       [-2.38122874, -0.44401572,  0.63509088,  1.04221819],
       [ 1.58474796, -0.20451141, -0.57013572, -2.4195694 ]])

In [71]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [72]:
#[조건식], [범위], [행, 열], [행시:행마, 열시:열마]
data[names == 'Bob']

array([[ 0.88053026, -1.02862681,  0.97283693, -0.66985979],
       [-2.24668949,  1.22677784,  0.773863  ,  1.27273805]])

In [73]:
data[names == 'Bob', 2:]

array([[ 0.97283693, -0.66985979],
       [ 0.773863  ,  1.27273805]])

In [74]:
data[names == 'Bob', 3]

array([-0.66985979,  1.27273805])

In [75]:
# != or ~
# 'Bob'이 아닌 요소를 선택하는 작업
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [76]:
data[~(names == 'Bob')]

array([[-0.18123833, -1.86329248,  0.34802926, -2.20922986],
       [ 0.16051297, -1.00486513,  0.68942233, -0.57080177],
       [ 0.9174606 , -1.88353752,  0.11698041,  0.28134936],
       [-2.38122874, -0.44401572,  0.63509088,  1.04221819],
       [ 1.58474796, -0.20451141, -0.57013572, -2.4195694 ]])

In [77]:
# 논리연산자 : &(and), |(or)
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [78]:
data[mask]

array([[ 0.88053026, -1.02862681,  0.97283693, -0.66985979],
       [ 0.16051297, -1.00486513,  0.68942233, -0.57080177],
       [-2.24668949,  1.22677784,  0.773863  ,  1.27273805],
       [ 0.9174606 , -1.88353752,  0.11698041,  0.28134936]])

In [79]:
data

array([[ 0.88053026, -1.02862681,  0.97283693, -0.66985979],
       [-0.18123833, -1.86329248,  0.34802926, -2.20922986],
       [ 0.16051297, -1.00486513,  0.68942233, -0.57080177],
       [-2.24668949,  1.22677784,  0.773863  ,  1.27273805],
       [ 0.9174606 , -1.88353752,  0.11698041,  0.28134936],
       [-2.38122874, -0.44401572,  0.63509088,  1.04221819],
       [ 1.58474796, -0.20451141, -0.57013572, -2.4195694 ]])

In [80]:
# data의 요소중에 음수인것은 모두 0으로 변환
data[data < 0] = 0
data

array([[0.88053026, 0.        , 0.97283693, 0.        ],
       [0.        , 0.        , 0.34802926, 0.        ],
       [0.16051297, 0.        , 0.68942233, 0.        ],
       [0.        , 1.22677784, 0.773863  , 1.27273805],
       [0.9174606 , 0.        , 0.11698041, 0.28134936],
       [0.        , 0.        , 0.63509088, 1.04221819],
       [1.58474796, 0.        , 0.        , 0.        ]])

In [81]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.34802926, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.63509088, 1.04221819],
       [1.58474796, 0.        , 0.        , 0.        ]])

### 팬시 색인 : 정수 배열을 사용한 색인

In [82]:
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i
    
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [83]:
arr[4]

array([4., 4., 4., 4.])

In [84]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [85]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [86]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [87]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [88]:
#[행, 열]
arr[[1, 5, 7, 2]][:,[0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [89]:
# 전치행렬(행과 열의 크기를 바꾸는 행렬)
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [91]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [92]:
A

array([[1, 2],
       [3, 4]])

In [93]:
B

array([[5, 6],
       [7, 8]])

In [94]:
A + B

array([[ 6,  8],
       [10, 12]])

In [95]:
A * B

array([[ 5, 12],
       [21, 32]])

In [96]:
# 행렬의 곱
np.dot(A, B)

array([[19, 22],
       [43, 50]])

### 유니버설 함수 : 배열의 각 원소를 빠르게 처리하는 함수
- ufunc 라고 불리기도 함

In [98]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [100]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [101]:
x = np.random.randn(8)
y = np.random.randn(8)

In [102]:
x

array([ 1.56765196,  0.83356891, -0.838391  ,  0.55181228, -0.35609152,
       -1.79250317,  1.65095994,  0.12977703])

In [103]:
y

array([ 0.46570584, -0.0933142 , -2.34303447,  0.49275123, -0.08238072,
       -1.06542494, -0.57243332,  0.21818499])

In [105]:
np.maximum(x, y)

array([ 1.56765196,  0.83356891, -0.838391  ,  0.55181228, -0.08238072,
       -1.06542494,  1.65095994,  0.21818499])

### 정렬

In [106]:
arr = np.random.randn(6)
arr

array([-1.56098196,  0.94607386,  0.67157671, -0.74998939,  0.13441466,
        1.34011371])

In [107]:
arr.sort()
arr

array([-1.56098196, -0.74998939,  0.13441466,  0.67157671,  0.94607386,
        1.34011371])

In [108]:
# np.unique()
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [109]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [110]:
ints = np.array([3, 3, 3, 4, 4, 1, 1, 2, 2])
np.unique(ints)

array([1, 2, 3, 4])

In [111]:
sorted(set(names))

['Bob', 'Joe', 'Will']