In [1]:
# 표준 라이브러리 로딩
import numpy as np
import pandas as pd
# from pandas import Series, DataFrame

In [2]:
# Series : 1차원 배열, index + values
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2['a']

-5

In [7]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [9]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [10]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [11]:
'b' in obj2

True

In [12]:
'e' in obj2

False

In [13]:
# 파이썬의 사전을 이용해서 Series를 생성
# 사전에서 key가 Series의 index가 된다.
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [14]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [15]:
# 결측값을 찾는 함수 : isnull(), notnull()
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [16]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [17]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [18]:
# name 속성
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [19]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [21]:
# index 변경
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame
- 표형태의 자료구조
- 여러개의 컬럼이 존재하고, 각 컬럼은 서로 다른 값을 담을 수 있다.
- 2차원 배열

In [22]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year':[2000, 2001, 2002, 2001, 2002, 2003],
       'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.7]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.7

In [23]:
# head(), tail() : 데이터프레임의 내용을 앞, 뒷단 5개의 row를 표시
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [24]:
frame.head(3)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [25]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.7

In [27]:
frame2 = pd.DataFrame(data, 
                      columns=['year', 'state', 'pop', 'debt'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.7  NaN

In [28]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [29]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [30]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [31]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [32]:
# 특정 행은 위치나 loc속성
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [33]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.7  16.5

In [34]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.7   5.0

In [35]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.7   NaN

In [36]:
# del 예약어를 통해 컬럼을 삭제
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.7   NaN    False

In [37]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.7   NaN

In [38]:
# 중첩된 사전을 이용한 데이터프레임 생성
pop = {'Navada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

Navada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [39]:
frame3.T

2000  2001  2002
Navada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [40]:
pd.DataFrame(pop, index = [2001,2002,2003])

Navada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [42]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Navada':frame3['Navada'][:2]}
pd.DataFrame(pdata)

Ohio  Navada
2000   1.5     NaN
2001   1.7     2.4

In [43]:
frame3

Navada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [44]:
# name 속성
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Navada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [45]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [47]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.7, nan]], dtype=object)

### DataFrame의 인덱스

In [48]:
obj = pd.Series(range(3), index = ['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [49]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [50]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [51]:
index[1:]

Index(['b', 'c'], dtype='object')

In [52]:
# 색인 객체는 변경이 불가능하다.
index[1] = 'd'

TypeError: Index does not support mutable operations

In [53]:
# 재색인 : reindex
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [54]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [55]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [57]:
# 누락된 값을 직전의 값으로 채워주는 역할
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [58]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index = ['a','c','d'],
                    columns = ['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [59]:
frame2 = frame.reindex(['a', 'b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [60]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [61]:
obj = pd.Series(np.arange(5.), index = ['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [62]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [65]:
obj.drop(['d','c'], inplace=True)

In [66]:
obj

a    0.0
b    1.0
e    4.0
dtype: float64

In [67]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [68]:
data.drop(['Colorado', 'Ohio'])  # axis = 0 생략된 것

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [69]:
# 컬럼을 삭제할 경우 반드시 축(axis)을 넘겨줘야 한다.
data.drop('two', axis=1)  # axis='columns'

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [70]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [71]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [72]:
obj = pd.Series(np.arange(4.), index = ['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [73]:
obj[1]

1.0

In [74]:
obj['b']

1.0

In [75]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [76]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [77]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [78]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [79]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [81]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [82]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [83]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [84]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [85]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [86]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [87]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [88]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [89]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [90]:
# loc, iloc 속성
# loc : 축 이름을 선택할 때
# iloc : 정수 인덱스를 선택할 때

In [91]:
# [행, 열]
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [92]:
data.iloc[1, [1, 2]]

two      5
three    6
Name: Colorado, dtype: int32

In [93]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [94]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [95]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [96]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [97]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [98]:
ser[-1]

KeyError: -1

In [99]:
ser2 = pd.Series(np.arange(3.), index = ['a','b','c'])
ser2[-1]

2.0

In [100]:
ser[:1]

0    0.0
dtype: float64

In [101]:
# 라벨
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [102]:
# 정수색인
ser.iloc[:1]

0    0.0
dtype: float64

### 산술 연산

In [106]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a','c','d','e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a','c','e','f','g'])

In [107]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [108]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [109]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [110]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),
                  columns = list('bcd'),
                  index = ['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                  columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [111]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [112]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [113]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [114]:
df1 = pd.DataFrame({'A':[1, 2]})
df2 = pd.DataFrame({'B':[3,4]})

In [115]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [116]:
df1.add(df2, fill_value = 0)

A    B
0  1.0  3.0
1  2.0  4.0

In [117]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [118]:
arr[0]

array([0., 1., 2., 3.])

In [119]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [120]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                  columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

series = frame.iloc[0]

In [121]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [122]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [123]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [124]:
series2 = pd.Series(range(3), index=['b','e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [125]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [127]:
frame = pd.DataFrame(np.random.randn(4,3),
                  columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.764245  2.265097 -1.094267
Ohio    0.279054 -1.257463 -1.390904
Texas   0.531575  0.791722 -0.353870
Oregon -0.815922  0.810810 -1.938641

In [128]:
np.abs(frame)

b         d         e
Utah    0.764245  2.265097  1.094267
Ohio    0.279054  1.257463  1.390904
Texas   0.531575  0.791722  0.353870
Oregon  0.815922  0.810810  1.938641

In [129]:
# frame 데이터에서 각 로우마다 최대값에서 최소값을 뺀 결과값을 추출하려면
# apply() : 특정 함수를 이용하여 반복적인 계산을 수행할 때 사용한다.
# lambda 입력 : 출력
f = lambda x : x.max() - x.min()
frame.apply(f)

b    1.347496
d    3.522561
e    1.584771
dtype: float64

In [130]:
frame.apply(f, axis = 'columns')

Utah      3.359365
Ohio      1.669958
Texas     1.145592
Oregon    2.749451
dtype: float64

In [131]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])

frame.apply(f)

b         d         e
min -0.815922 -1.257463 -1.938641
max  0.531575  2.265097 -0.353870

In [132]:
frame

b         d         e
Utah   -0.764245  2.265097 -1.094267
Ohio    0.279054 -1.257463 -1.390904
Texas   0.531575  0.791722 -0.353870
Oregon -0.815922  0.810810 -1.938641

In [134]:
fmt = lambda x : '%.2f' % x
frame.applymap(fmt)

b      d      e
Utah    -0.76   2.27  -1.09
Ohio     0.28  -1.26  -1.39
Texas    0.53   0.79  -0.35
Oregon  -0.82   0.81  -1.94

In [135]:
frame['e'].map(fmt)

Utah      -1.09
Ohio      -1.39
Texas     -0.35
Oregon    -1.94
Name: e, dtype: object

### GroupBy 객체

In [2]:
df = pd.DataFrame({'key':['a','b','c']*4,
                  'value':np.arange(12.)})
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [4]:
# 'key'별로 평균을 계산하여 추출하시오.
tmp = df.groupby('key').value
tmp.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [5]:
# lambda 입력 : 출력
tmp.transform(lambda x : x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [6]:
tmp.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [7]:
# 정규화
def normalize(x):
    return (x - x.mean()) / x.std()

In [8]:
tmp.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [9]:
tmp.apply(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64