### 0. 대표적인 데이터 분석용 라이브러리
- 넘파이(Numpy) : 넘파이 배열, 리스트 확장판
- 판다스(Pandas) : 테이블 형태의 데이터 처리, 딕셔너리의 확장판
- 맷플롯립(Matplotlib) : 파이썬의 시각화를 담당하는 라이브러리
- 외부 모듈을 설치할 경우는 파이썬의 파이프 연산을 통해서 설치한다.
      pip install numpy pandas matplotlib

In [2]:
# list
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 0]
print(a + b) # append

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [3]:
# 라이브러리 로딩
import numpy as np
arr1 = np.array(a)
arr2 = np.array(b)
print(arr1 + arr2)

[ 7  9 11 13  5]


In [5]:
print(type(arr1))
print(type(a))

<class 'numpy.ndarray'>
<class 'list'>


In [6]:
# 넘파일 배열의 크기. shape
arr1.shape

(5,)

In [7]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(ar)

[0 1 2 3 4 5 6 7 8 9 0]


In [8]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = []

for i in data:
    answer.append(i * 2)
    
# answer = [i * 2 for i in data]
    
print(answer)

In [9]:
x = np.array(data)
print(x * 2)

[ 0  2  4  6  8 10 12 14 16 18]


In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [11]:
print(a + b)
print(a - b)
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10))

[11 22 33]
[ -9 -18 -27]
[False  True False]
[False  True  True]
[False  True False]


In [12]:
# 2차원 배열 : 행(가로 row), 열(세로 column)
a = [[0, 1, 2], [3, 4, 5]]
print(a)

c = np.array([[0, 1, 2], [3, 4, 5]]) # 2 * 3 Array
print(c)

[[0, 1, 2], [3, 4, 5]]
[[0 1 2]
 [3 4 5]]


In [14]:
# 행의 갯수
print(len(a))
print(len(c))

# 열의 갯수
print(len(c[0]))

print(c.shape)

2
2
3
(2, 3)


In [16]:
# 3차원 배열 생성 2 * 3 * 4 (면, 행, 열)]
d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
              [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]])
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [17]:
print(len(d), len(d[0]), len(d[0][0])) # 면, 행, 열

2 3 4


In [18]:
print(d.shape)

(2, 3, 4)


In [19]:
# 배열의 차원-ndim과 크기(속성) - shape
print(d.ndim)

3


In [4]:
# 배열의 인덱싱
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [5]:
a[-1]

4

In [6]:
b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 * 3

In [7]:
# [조건식] [행, 열]
print(b[0, 0])
print(b[1, 1])

# 마지막 행, 마지막 열
print(b[-1, -1])

0
4
5


In [9]:
# Slicing
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(c)

# 첫번째행 [행, 열], [시작값:마지막값]
print(c[0, :])
# 두번째 열 전체
print(c[:,1])
# 두번째 행, 두번째열부터 끝 열까지
print(c[1, 1:])

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
[2 6]
[6 7 8]


In [10]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
print(a[idx])

[0 2 4 6 8]


In [13]:
print(a % 2)
print(a % 2 == 0)
print(a[a % 2 == 0])

[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [15]:
# 넘파이 자료형 type => dtype, 배열의 자료형을 읽어오는 속성
xp = np.array([1, 2, 3])
print(xp.dtype)
print(type(xp))

int32
<class 'numpy.ndarray'>


In [16]:
xp = np.array([1.0, 2.0, 3.0])
print(xp.dtype)

x = np.array([1, 2, 3.0])
print(x.dtype)

float64
float64


In [18]:
x = np.array([1, 2, 3], dtype = 'f') # f(float)
x.dtype

dtype('float32')

In [21]:
# u(unsign int) : 부호 없는 정수 / U(unicode) : 유니코드 - 문자열?
x = np.array([1, 2, 3], dtype = 'U') 
print(x.dtype)
print(x)

<U1
['1' '2' '3']


In [22]:
# Inf와 NaN
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([  0.,  inf, -inf,  nan])

In [23]:
np.log(0)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [24]:
# 배열 생성 명령 : 단순한 배열을 생성하는 명령어
# zeros, ones
a = np.zeros(5)
print(a)

b = np.zeros((2, 3))
print(b)

c = np.zeros((5, 2), dtype = 'i')
print(c)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [27]:
# 문자열 배열도 가능, 단 모든 원소의 문자열 크기가 같아야한다.
d = np.zeros(5, dtype = 'U4')
print(d)

['' '' '' '' '']


In [28]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCDE'
d[3] = 'ABCDEFGH'
print(d)

['abc' 'abcd' 'ABCD' 'ABCD' '']


In [30]:
e = np.ones((2, 3, 4), dtype = 'i')
print(e)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [31]:
# ones_like, zeros_like : 배열의 크기를 명시하지 않고 다른 배열의 크기 가져다 씀
f = np.ones_like(b)
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
# empty : 배열을 초기화
g = np.empty((4, 3))
print(g)

[[2.12199579e-314 2.12199579e-314 2.12199579e-314]
 [2.12199579e-314 2.12199579e-314 2.12199579e-314]
 [2.12199579e-314 2.12199579e-314 2.12199579e-314]
 [2.12199579e-314 2.12199579e-314 2.12199579e-314]]


In [35]:
# arange : range의 numpy 버전
np.arange(10) # 0, ... n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(3, 21, 2) # 시작, 끝(포함X), 증감

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
# linspace - 선형 구간, logspace 명령 - 로그구간
np.linspace(0, 100, 5) # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [39]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [40]:
# 배열의 크기 변형
# shape : 배열의 속성 확인
# reshape(row, column)
a = np.arange(12) # 0...11
print(a)

b = a.reshape(3, 4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [41]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [43]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [46]:
x = np.arange(5)
print(x)

x = x.reshape(1, 5)
print(x)

x = x.reshape(5, 1)
print(x)

[0 1 2 3 4]
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [47]:
# Vector화 연산
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a == b)
print(a >= b)

[5 4 5 8]
[-3  0  1  0]
[ 4  4  6 16]
[0.25 1.   1.5  1.  ]
[False  True False  True]
[False  True  True  True]


In [48]:
# all() : 모든 요소를 대상으로 비교하는 작업
np.all(a == b)

False

In [49]:
c = np.array([1, 2, 3, 4])
np.all(a == c)

True

In [50]:
x = np.arange(12).reshape(3, 4)
print(x * 100)

[[   0  100  200  300]
 [ 400  500  600  700]
 [ 800  900 1000 1100]]


In [51]:
# 내장함수
# min, max, sum, mean, median, std, var, all, any

x = np.array([1, 2, 3, 4])

print(np.sum(x))

10


In [54]:
# argmin - 최소값의 위치, argmax - 최대값의 위치
print(np.min(x))
print(np.argmin(x))
print(np.max(x))
print(np.argmax(x))
print(x.mean()) # 평균
print(np.mean(x))
print(np.median(x)) # 중앙값
print(np.all([True,True,False]))
print(np.any([True,True,False]))

1
0
4
3
2.5
2.5
2.5
False
True


In [55]:
x = np.array([[1, 2], [3, 4]])
print(np.sum(x))
print(x.sum())
print(x.sum(axis = 0)) # 열
print(x.sum(axis = 1)) # 행

10
10
[4 6]
[3 7]


In [ ]:
a = np.array([[1, 2], [3, 4]], dtype = 'i')
b = np.array([[1, 2], [3, 4]], dtype = 'i')