In [1]:
# count : 데이터 개수
# 평균 : mean, average
# 분산 : var, varience
# 표준편차 : std, stndart, deviation
# 최대값 : maximum
# 최소값 : minimum
# 중앙값 : midian
# 사분위수 : quartile

In [2]:
import numpy as np
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 5, 2,
              -15, 8, 3, 5, 4, 15, -1, 4, -24, 7, 9, 
             -6, 23, -13])

In [3]:
len(x)

24

In [4]:
np.mean(x)

4.291666666666667

In [5]:
np.var(x)

129.62326388888889

In [6]:
np.std(x)

11.385221292925706

In [7]:
np.max(x)

23

In [8]:
np.min(x)

-24

In [9]:
np.median(x)

5.0

In [11]:
# 백분위수(percentile)
np.percentile(x, 0) #최소값

-24.0

In [12]:
np.percentile(x, 100) #최대값

23.0

In [13]:
np.percentile(x, 25) #1사분위 수

-0.25

In [14]:
np.percentile(x, 50) # 2사분위수

5.0

In [15]:
np.percentile(x, 75) # 3사분위수

10.0

In [16]:
# 난수 발생 
# rand() : 0과 1사이의 난수를 발생시키는 함수
np.random.rand(5)

array([0.02068769, 0.00632879, 0.60608006, 0.51707235, 0.81219128])

In [17]:
np.random.rand(10)

array([0.43627671, 0.96074677, 0.92177477, 0.69184492, 0.33785941,
       0.76947585, 0.18268288, 0.6785793 , 0.39068754, 0.93033299])

In [18]:
np.random.rand(10)

array([0.17458428, 0.70694427, 0.98553946, 0.3931833 , 0.81656172,
       0.1995296 , 0.22278093, 0.40574108, 0.62887109, 0.69082229])

In [19]:
# shuffle() : 데이터를 섞는다.

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.random.shuffle(x)
x

array([8, 9, 6, 4, 0, 1, 5, 3, 7, 2])

In [22]:
np.random.choice(5, 5)

array([2, 3, 2, 4, 2])

In [23]:
np.random.choice(5, 5, replace = False) # 중복방지!

array([0, 1, 4, 2, 3])

In [24]:
np.random.choice(5, 5, p = [0.1, 0, 0.3, 0.6, 0])

array([2, 3, 3, 2, 2], dtype=int64)

In [25]:
# rand : 0부터 1사이의 균일 분포
# randn : 표준 정규 분포
# randint : 균일분포의 정수난수

In [28]:
np.random.rand(10)

array([0.85369218, 0.41487929, 0.53237631, 0.11600685, 0.86097235,
       0.58248454, 0.66233016, 0.8835594 , 0.74507102, 0.9087595 ])

In [29]:
np.random.rand(3, 5) # 3행, 5열 (행, 열)

array([[0.02569877, 0.10380517, 0.9313591 , 0.23100175, 0.97977629],
       [0.14212357, 0.1774799 , 0.03661076, 0.0795911 , 0.61728883],
       [0.33998608, 0.68053661, 0.3237036 , 0.63260733, 0.06523286]])

In [31]:
np.random.randn(10)

array([-1.08529582,  0.37548179,  0.19046209,  0.01840819, -0.04566443,
        1.66032292,  1.02716098,  0.18740013, -0.54875943,  0.65992103])

In [32]:
np.random.randn(3, 5)

array([[-0.89390419, -1.00430228, -0.27375382, -1.36501501,  0.71410543],
       [-1.66190331, -0.06490493,  0.74308503,  1.22529874, -0.32572713],
       [-0.36363825, -0.30532877,  0.99978971,  0.36489177, -0.04644022]])

In [33]:
# randint(low, high, size)
np.random.randint(10, size = 10) # 0~9 10개의 난수

array([6, 3, 3, 6, 7, 4, 7, 3, 5, 9])

In [34]:
np.random.randint(10, 20, size = 10) # 10~19 10개의 난수

array([13, 13, 18, 17, 15, 18, 19, 10, 15, 11])

In [35]:
np.random.randint(10, 20, size = (3, 5))

array([[13, 19, 19, 11, 15],
       [15, 11, 12, 12, 16],
       [17, 16, 15, 18, 17]])