In [8]:
import numpy as np
w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

In [2]:
w_r = np.flip(w)
w_r

array([3, 5, 1, 2])

In [4]:
w_r = w[::-1]
w_r

array([3, 5, 1, 2])

In [5]:
# 한 칸 씩 이동하며 합성곱을 수행하는 함수 : 정곱
for i in range(6):
    print(np.dot(x[i:i+4], w_r))

63
48
49
28
21
20


In [6]:
from scipy.signal import convolve

convolve(x, w, mode='valid')

array([63, 48, 49, 28, 21, 20])

In [11]:
x = np.arange(12).reshape(3, 4)
x.shape

(3, 4)

In [12]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
x.reshape(-1, 1)  # -1(가변, 뒷 숫자부터 정하기)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [18]:
x.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])